{
 "title": "Go HTTP Server Metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Request rate by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_request_duration_seconds_count{job=\"$job\"}[30s]))"
    }
   ]
  },
  {
   "title": "Percentile 90 of each handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,\r\n    sum(\r\n        rate(http_request_duration_seconds_bucket{job=\"$job\"}[10m])\r\n    ) by (handler, le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"5..\", job=\"$job\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile 99 of the whole service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n    rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\"} - go_memstats_other_sys_bytes{job=\"$job\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\"} - go_memstats_frees_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}"
    }
   ]
  }
 ]
}